### ISSUE TITLE
Doors are falling trough Map

### ISSUE THREAD

**Issue by Aspry1** [kibook/redm-object-spooner#31]
Hi Guys,

when i add some doors and edit them to be lock/unlockable they will fall trough the world.
Is there any specific option to fix them?

when i turn Collission off i can walk trough them :D
Didn't get em work as normal door.

**Comment by kibook** [comment]
I haven't found a way to make doors work spawning them via spooner. However, if you export your database to ymap and then stream the ymap, the doors will function properly: https://streamable.com/ynvrwl

This is only an option if it's your server that you can install new resources on, though.

**Comment by Aspry1** [comment]
Okay, thank you very much, i got my export string from my saved ones but how can i turn this in ymap (normaly iam not an mapper sry 4 maybe dump questions :D)

**Comment by Aspry1** [comment]
Btw i use GTA5 and trying to change your xml to rerender for openiv with that tool https://ro.gta5-mods.com/tools/mapeditor-2-ymap-converter

The direct ymap output wont work for openiv on gta5 :(

**Comment by kibook** [comment]
I'm not sure about OpenIV, but you can stream plain XML ymaps with FiveM and RedM, they don't need to be converted to the binary format.

**Comment by Aspry1** [comment]
Hm i'am sorry bot then iam to dump to do it.

even the xml format in the resource folder or the ymap.xml (as ymap export of spooner) wont load correctly :/

Maybe it is because i delete some items of the original map?

**Comment by kibook** [comment]
Try changing the extension to `.ymap` instead of `.xml`.

ymaps can't remove objects so things you deleted won't be removed by streaming the ymap. You would need to modify the existing base game ymap that spawns those objects in the first place.

**Comment by Validus-Tommy** [comment]
> ymaps can't remove objects so things you deleted won't be removed by streaming the ymap. You would need to modify the existing base game ymap that spawns those objects in the first place.

How would someone go about doing this using Spooner? Is it possible? I want to clean up the base game ymap and remove objects and then stream them to a server.

**Comment by Aspry1** [comment]
yeah i tried these works live on spooner rly well.

I have the files but cant edit them right on CodeWalker because they are not loading in it. So thats the reason why iam asking :)

Even the ymap file wont stream correctly when i export it from spooner as ymap (only added a pizza)
