### ISSUE TITLE
Position and Rotation numbers

### ISSUE THREAD

**Issue by OhSuty** [kibook/redm-object-spooner#36]
I used Menyoo to create emotes with props attach to it, and the numbers for the prop rotation and position were accurate but when I use the spooner numbers is not, any help with that

**Comment by kibook** [comment]
Could you provide an example, with the prop, bone it is attached to, position and rotation?

I did a quick test and it seems to work fine for me:
![FiveM_b2545_GTAProcess_yMGo2obKUx](https://user-images.githubusercontent.com/2752539/173203109-ec7c57c3-f186-4ad2-8a49-298b15ebebde.jpg)
![FiveM_b2545_GTAProcess_2lmRB80OW3](https://user-images.githubusercontent.com/2752539/173203115-d58d8446-7d3f-4669-af92-121c47a098c5.jpg)

**Comment by OhSuty** [comment]
ohh ok ok now I realized, is just that the spooner is missing some 0 but I just can add them in, never mind is gucci and is way better cause it has the bone name
