### ISSUE TITLE
I am struggling to get spooner to work on rdr3

### ISSUE THREAD

**Issue by CWhiteTM** [kibook/redm-object-spooner#39]
I am just struggling with getting it to work on my server When I start my server I get this 

[ citizen-server-impl] Started resource redm-uiprompt
[    c-resources-core] Could not find dependency uiprompt for resource spooner.
[ citizen-server-impl] Couldn't start resource spooner.

where exactly do I put this at in the server.cfg

exec @spooner/permissions.cfg
start spooner

I am struggling on where I put this. I'm also new at this so I'm trying to learn as best as I can.

**Comment by kibook** [comment]
You need to rename the "redm-uiprompt" resource to just "uiprompt".

**Comment by CWhiteTM** [comment]
Wow, it was that simple! Thank you!!!

**Comment by CWhiteTM** [comment]
so I got spooner on my server but when I do /spooner to toggle it nothing happens. would you know how to fix that?
